"""Add column last_name to User model

Revision ID: 0be29a8b6bdc
Revises: 4fc08b15ccf7
Create Date: 2020-08-31 12:06:42.755573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0be29a8b6bdc'
down_revision = '4fc08b15ccf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
