"""Add User model

Revision ID: 2c6d6539a727
Revises: 0be29a8b6bdc
Create Date: 2020-08-31 12:14:35.235477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c6d6539a727'
down_revision = '0be29a8b6bdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
