"""Add User model

Revision ID: 44de317f8fb8
Revises: 31c5fdb917d4
Create Date: 2020-08-31 12:19:13.427014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44de317f8fb8'
down_revision = '31c5fdb917d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
